In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('/content/Alphabets_data.csv')
df

,letter,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
0,T,2,8,3,5,1,8,13,0,6,6,10,8,0,8,0,8
1,I,5,12,3,7,2,10,5,5,4,13,3,9,2,8,4,10
2,D,4,11,6,8,6,10,6,2,6,10,3,7,3,7,3,9
3,N,7,11,6,6,3,5,9,4,6,4,4,10,6,10,2,8
4,G,2,1,3,1,1,8,6,6,6,6,5,9,1,7,5,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,D,2,2,3,3,2,7,7,7,6,6,6,4,2,8,3,7
19996,C,7,10,8,8,4,4,8,6,9,12,9,13,2,9,3,7
19997,T,6,9,6,7,5,6,11,3,7,11,9,5,2,12,2,4
19998,S,2,3,4,2,1,8,7,2,6,10,6,8,1,9,5,8
19999,A,4,9,6,6,2,9,5,3,1,8,1,8,2,7,2,8

Preprossing

In [4]:
df.describe()

,xbox,ybox,width,height,onpix,xbar,ybar,x2bar,y2bar,xybar,x2ybar,xy2bar,xedge,xedgey,yedge,yedgex
count,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000,20000.000000,20000.000000,20000.000000,20000.000000,20000.00000
mean,4.023550,7.035500,5.121850,5.37245,3.505850,6.897600,7.500450,4.628600,5.178650,8.282050,6.45400,7.929000,3.046100,8.338850,3.691750,7.80120
std,1.913212,3.304555,2.014573,2.26139,2.190458,2.026035,2.325354,2.699968,2.380823,2.488475,2.63107,2.080619,2.332541,1.546722,2.567073,1.61747
min,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000
25%,3.000000,5.000000,4.000000,4.00000,2.000000,6.000000,6.000000,3.000000,4.000000,7.000000,5.00000,7.000000,1.000000,8.000000,2.000000,7.00000
50%,4.000000,7.000000,5.000000,6.00000,3.000000,7.000000,7.000000,4.000000,5.000000,8.000000,6.00000,8.000000,3.000000,8.000000,3.000000,8.00000
75%,5.000000,9.000000,6.000000,7.00000,5.000000,8.000000,9.000000,6.000000,7.000000,10.000000,8.00000,9.000000,4.000000,9.000000,5.000000,9.00000
max,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.00000,15.000000,15.000000,15.000000,15.000000,15.00000

In [5]:
df.isnull().sum()

letter    0
xbox      0
ybox      0
width     0
height    0
onpix     0
xbar      0
ybar      0
x2bar     0
y2bar     0
xybar     0
x2ybar    0
xy2bar    0
xedge     0
xedgey    0
yedge     0
yedgex    0
dtype: int64

In [7]:
df.shape[0]

20000

In [8]:
df['letter'].value_counts()

letter
U    813
D    805
P    803
T    796
M    792
A    789
X    787
Y    786
N    783
Q    783
F    775
G    773
E    768
B    766
V    764
L    761
R    758
I    755
O    753
W    752
S    748
J    747
K    739
C    736
H    734
Z    734
Name: count, dtype: int64

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.columns[1:]
df[num_col]=scaler.fit_transform(df[num_col])

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   letter  20000 non-null  object
 1   xbox    20000 non-null  float64
 2   ybox    20000 non-null  float64
 3   width   20000 non-null  float64
 4   height  20000 non-null  float64
 5   onpix   20000 non-null  float64
 6   xbar    20000 non-null  float64
 7   ybar    20000 non-null  float64
 8   x2bar   20000 non-null  float64
 9   y2bar   20000 non-null  float64
 10  xybar   20000 non-null  float64
 11  x2ybar  20000 non-null  float64
 12  xy2bar  20000 non-null  float64
 13  xedge   20000 non-null  float64
 14  xedgey  20000 non-null  float64
 15  yedge   20000 non-null  float64
 16  yedgex  20000 non-null  float64
dtypes: float64(16), object(1)
memory usage: 2.6+ MB

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

x = df.drop('letter', axis=1)
y = df['letter']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(x, y_encoded, test_size=0.2, random_state=42)

In [12]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(16000, 16) (4000, 16) (16000,) (4000,)

# Model Building

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
model = Sequential()
model.add(Dense(64, input_shape=(16,), activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# Compile model
model.compile(optimizer='adam', loss='kl_divergence', metrics=['accuracy'])
# Fit the model
history=model.fit(X_train,y_train,validation_data=(X_test,y_test), epochs=100, batch_size=20)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0368 - loss: 0.1039 - val_accuracy: 0.0382 - val_loss: 1.1791e-05
Epoch 2/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0379 - loss: 7.2524e-06 - val_accuracy: 0.0382 - val_loss: 1.0131e-06
Epoch 3/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0392 - loss: 6.8019e-07 - val_accuracy: 0.0382 - val_loss: 1.6991e-07
Epoch 4/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0387 - loss: 1.1281e-07 - val_accuracy: 0.0382 - val_loss: 2.8562e-08
Epoch 5/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0373 - loss: 5.5223e-09 - val_accuracy: 0.0382 - val_loss: -1.7661e-08
Epoch 6/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0399 - loss: -2.7846e-08 - val_accuracy: 0.0382 - val_loss: -3.8344e-08
Epoch 7/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0370 - loss: -4.1778e-08 - val_accuracy: 0.0382 - val_loss: -4.7791e-08
Epoch 8/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0370 - loss: -5.0462e-08 - val_accuracy: 0.0382 - val_loss: -5.2560e-08
Epoch 9/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0379 - loss: -5.7271e-08 - val_accuracy: 0.0382 - val_loss: -5.5242e-08
Epoch 10/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0382 - loss: -6.1265e-08 - val_accuracy: 0.0382 - val_loss: -5.6762e-08
Epoch 11/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0381 - loss: -6.2978e-08 - val_accuracy: 0.0382 - val_loss: -5.7656e-08
Epoch 12/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0379 - loss: -5.9242e-08 - val_accuracy: 0.0382 - val_loss: -5.8282e-08
Epoch 13/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0403 - loss: -6.2621e-08 - val_accuracy: 0.0382 - val_loss: -5.8788e-08
Epoch 14/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0359 - loss: -6.5803e-08 - val_accuracy: 0.0382 - val_loss: -5.9116e-08
Epoch 15/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0385 - loss: -6.2831e-08 - val_accuracy: 0.0382 - val_loss: -5.9354e-08
Epoch 16/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0390 - loss: -6.1671e-08 - val_accuracy: 0.0382 - val_loss: -5.9503e-08
Epoch 17/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0385 - loss: -6.4086e-08 - val_accuracy: 0.0382 - val_loss: -5.9563e-08
Epoch 18/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0368 - loss: -6.3785e-08 - val_accuracy: 0.0382 - val_loss: -5.9652e-08
Epoch 19/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0388 - loss: -5.8587e-08 - val_accuracy: 0.0382 - val_loss: -5.9682e-08
Epoch 20/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0384 - loss: -6.1150e-08 - val_accuracy: 0.0382 - val_loss: -5.9742e-08
Epoch 21/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0387 - loss: -6.4971e-08 - val_accuracy: 0.0382 - val_loss: -5.9742e-08
Epoch 22/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0375 - loss: -6.0715e-08 - val_accuracy: 0.0382 - val_loss: -5.9802e-08
Epoch 23/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0369 - loss: -6.0444e-08 - val_accuracy: 0.0382 - val_loss: -5.9802e-08
Epoch 24/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0383 - loss: -6.5875e-08 - val_accuracy: 0.0382 - val_loss: -5.9831e-08
Epoch 25/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0376 - loss: -6.6014e-08 - val_accuracy: 0.0382 - val_loss: -5.9861e-08
Epoch 26/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0412 - loss: -6.4542e-08 - val_accuracy: 0.0382 - val_loss: -5.9891e-08
Epoch 27/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0385 - loss: -6.2888e-08 - val_accuracy: 0.0382 - val_loss: -5.9891e-08
Epoch 28/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0392 - loss: -6.5512e-08 - val_accuracy: 0.0382 - val_loss: -5.9951e-08
Epoch 29/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0390 - loss: -6.5873e-08 - val_accuracy: 0.0382 - val_loss: -5.9951e-08
Epoch 30/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0391 - loss: -6.3691e-08 - val_accuracy: 0.0382 - val_loss: -5.9951e-08
Epoch 31/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0348 - loss: -6.3419e-08 - val_accuracy: 0.0382 - val_loss: -5.9980e-08
Epoch 32/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0382 - loss: -6.8321e-08 - val_accuracy: 0.0382 - val_loss: -5.9980e-08
Epoch 33/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0370 - loss: -6.7255e-08 - val_accuracy: 0.0382 - val_loss: -6.0010e-08
Epoch 34/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0400 - loss: -6.7304e-08 - val_accuracy: 0.0382 - val_loss: -6.0010e-08
Epoch 35/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0386 - loss: -6.7167e-08 - val_accuracy: 0.0382 - val_loss: -6.0010e-08
Epoch 36/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0386 - loss: -6.9571e-08 - val_accuracy: 0.0382 - val_loss: -6.0010e-08
Epoch 37/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0373 - loss: -6.1820e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 38/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0377 - loss: -6.8345e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 39/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0383 - loss: -6.1552e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 40/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0390 - loss: -6.4085e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 41/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0381 - loss: -6.8508e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 42/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0390 - loss: -6.2760e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 43/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0354 - loss: -6.3436e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 44/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0365 - loss: -6.3278e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 45/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0387 - loss: -6.8665e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 46/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0378 - loss: -6.8433e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 47/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0397 - loss: -6.8098e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 48/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0388 - loss: -6.6736e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 49/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0380 - loss: -6.9244e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 50/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0375 - loss: -6.8467e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 51/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0378 - loss: -6.4412e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 52/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.0371 - loss: -5.9672e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 53/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0396 - loss: -6.4618e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 54/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0392 - loss: -6.7537e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 55/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0371 - loss: -6.4959e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 56/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0393 - loss: -6.5691e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 57/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0409 - loss: -5.9414e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 58/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 6ms/step - accuracy: 0.0382 - loss: -6.2066e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 59/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0370 - loss: -6.2410e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 60/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0381 - loss: -6.1277e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 61/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0350 - loss: -6.1926e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 62/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0378 - loss: -6.3334e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 63/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0389 - loss: -6.2351e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 64/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0387 - loss: -6.8361e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 65/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0394 - loss: -6.4356e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 66/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0359 - loss: -6.4147e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 67/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.0378 - loss: -6.3532e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 68/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 5ms/step - accuracy: 0.0379 - loss: -6.2749e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 69/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0395 - loss: -6.1766e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 70/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0363 - loss: -6.2988e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 71/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0368 - loss: -6.6459e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 72/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0399 - loss: -6.8587e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 73/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0369 - loss: -6.3818e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 74/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.0389 - loss: -6.7417e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 75/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0377 - loss: -6.4679e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 76/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 6s 5ms/step - accuracy: 0.0393 - loss: -6.1891e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 77/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0395 - loss: -6.1440e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 78/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0350 - loss: -6.7034e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 79/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0370 - loss: -6.6139e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 80/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0415 - loss: -6.4208e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 81/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0397 - loss: -5.9985e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 82/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0373 - loss: -6.6661e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 83/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0412 - loss: -6.6968e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 84/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0386 - loss: -6.2002e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 85/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0384 - loss: -6.4884e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 86/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0383 - loss: -6.6949e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 87/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0399 - loss: -6.1817e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 88/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0380 - loss: -6.6599e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 89/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0385 - loss: -6.5259e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 90/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0408 - loss: -6.4220e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 91/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0371 - loss: -6.6882e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 92/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.0415 - loss: -6.1851e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 93/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.0381 - loss: -6.4329e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 94/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0387 - loss: -5.9294e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 95/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0359 - loss: -6.9264e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 96/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.0388 - loss: -6.0759e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 97/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0391 - loss: -6.2803e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 98/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0385 - loss: -6.3938e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 99/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0395 - loss: -6.2434e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08
Epoch 100/100
800/800 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0365 - loss: -6.6796e-08 - val_accuracy: 0.0382 - val_loss: -6.0040e-08

In [15]:
scores = model.evaluate(X_test, y_test)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0435 - loss: -5.9738e-08
compile_metrics: 3.82%

# Hyper Parameter Tuning Using Ephos and Batch Size

In [18]:
pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from scikeras) (3.4.1)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.10/dist-packages (from scikeras) (1.5.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (1.26.4)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (13.9.3)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (3.12.1)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (0.13.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->scikeras) (24.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.5.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.10/dist-packages (from optree->keras>=3.2.0->scikeras) (4.12.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->scikeras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [19]:
from scikeras.wrappers import KerasClassifier
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.optimizers import Adam
import warnings
warnings.filterwarnings('ignore')
# create model
def create_model():
    model = Sequential(name='Hypterparameter-Tuning-Dummy')
    model.add(Dense(64, input_dim=16, kernel_initializer='uniform', activation='relu'))
    model.add(Dense(32,kernel_initializer='uniform', activation='relu'))
    model.add(Dense(1, kernel_initializer='uniform', activation='sigmoid'))

    adam=Adam(learning_rate=0.01)
    model.compile(loss='kl_divergence', optimizer=adam, metrics=['accuracy'])
    return model
# Create the model
from sklearn.model_selection import KFold
model = KerasClassifier(build_fn = create_model,verbose = 1)
# Define the grid search parameters
batch_size = [20,25,30]
epochs = [10,20,40]
# Make a dictionary of the grid search parameters
param_grid = dict(batch_size = batch_size,epochs = epochs)
# Build and fit the GridSearchCV
grid = GridSearchCV(estimator = model,param_grid = param_grid,cv = KFold(n_splits=3),verbose = 10)
grid_result = grid.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV 1/3; 1/9] START batch_size=20, epochs=10....................................
Epoch 1/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 9s 6ms/step - accuracy: 0.0368 - loss: 0.0397
Epoch 2/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 7s 10ms/step - accuracy: 0.0389 - loss: -6.0051e-08
Epoch 3/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0416 - loss: -6.6080e-08
Epoch 4/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0354 - loss: -6.3676e-08
Epoch 5/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0377 - loss: -6.3875e-08
Epoch 6/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0377 - loss: -6.5494e-08
Epoch 7/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0401 - loss: -6.7410e-08
Epoch 8/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0396 - loss: -5.6979e-08
Epoch 9/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0355 - loss: -5.8553e-08
Epoch 10/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0357 - loss: -6.0754e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[CV 1/3; 1/9] END .....batch_size=20, epochs=10;, score=0.041 total time=  32.3s
[CV 2/3; 1/9] START batch_size=20, epochs=10....................................
Epoch 1/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0398 - loss: 0.0503
Epoch 2/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0417 - loss: -6.3223e-08
Epoch 3/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0410 - loss: -6.3500e-08
Epoch 4/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0423 - loss: -6.0055e-08
Epoch 5/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0347 - loss: -6.1519e-08
Epoch 6/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0384 - loss: -5.8822e-08
Epoch 7/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0421 - loss: -6.2453e-08
Epoch 8/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0426 - loss: -6.8163e-08
Epoch 9/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0407 - loss: -5.5698e-08
Epoch 10/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0429 - loss: -5.8961e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[CV 2/3; 1/9] END .....batch_size=20, epochs=10;, score=0.041 total time=  15.5s
[CV 3/3; 1/9] START batch_size=20, epochs=10....................................
Epoch 1/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0375 - loss: 0.0481
Epoch 2/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0370 - loss: -4.7799e-08
Epoch 3/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0390 - loss: -4.9092e-08
Epoch 4/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0354 - loss: -6.0389e-08
Epoch 5/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0377 - loss: -5.7605e-08
Epoch 6/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0372 - loss: -6.3401e-08
Epoch 7/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0392 - loss: -6.0701e-08
Epoch 8/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0371 - loss: -6.3661e-08
Epoch 9/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0348 - loss: -6.6839e-08
Epoch 10/10
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0361 - loss: -7.0498e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[CV 3/3; 1/9] END .....batch_size=20, epochs=10;, score=0.037 total time=  15.2s
[CV 1/3; 2/9] START batch_size=20, epochs=20....................................
Epoch 1/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0372 - loss: 0.0502
Epoch 2/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0388 - loss: -5.4030e-08
Epoch 3/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0414 - loss: -4.8772e-08
Epoch 4/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0403 - loss: -5.4527e-08
Epoch 5/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0398 - loss: -5.4525e-08
Epoch 6/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0390 - loss: -5.6662e-08
Epoch 7/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0346 - loss: -5.1591e-08
Epoch 8/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0380 - loss: -5.1934e-08
Epoch 9/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0378 - loss: -5.5822e-08
Epoch 10/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0341 - loss: -5.6683e-08
Epoch 11/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0341 - loss: -5.4788e-08
Epoch 12/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0366 - loss: -5.2964e-08
Epoch 13/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0384 - loss: -5.5289e-08
Epoch 14/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0391 - loss: -5.8024e-08
Epoch 15/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0392 - loss: -5.0842e-08
Epoch 16/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0354 - loss: -5.0948e-08
Epoch 17/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0395 - loss: -5.8359e-08
Epoch 18/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0390 - loss: -5.8335e-08
Epoch 19/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0417 - loss: -6.1946e-08
Epoch 20/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0363 - loss: -6.1141e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
[CV 1/3; 2/9] END .....batch_size=20, epochs=20;, score=0.041 total time=  35.4s
[CV 2/3; 2/9] START batch_size=20, epochs=20....................................
Epoch 1/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0392 - loss: 0.0436
Epoch 2/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0402 - loss: -5.6947e-08
Epoch 3/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0422 - loss: -6.7189e-08
Epoch 4/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0376 - loss: -6.2298e-08
Epoch 5/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0389 - loss: -5.8565e-08
Epoch 6/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0369 - loss: -6.7217e-08
Epoch 7/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0411 - loss: -5.8044e-08
Epoch 8/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0434 - loss: -6.0265e-08
Epoch 9/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0390 - loss: -6.1846e-08
Epoch 10/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0388 - loss: -6.0005e-08
Epoch 11/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0415 - loss: -6.2588e-08
Epoch 12/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0383 - loss: -5.8433e-08
Epoch 13/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.0387 - loss: -5.9966e-08
Epoch 14/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0387 - loss: -6.0911e-08
Epoch 15/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0436 - loss: -5.8182e-08
Epoch 16/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0363 - loss: -6.1927e-08
Epoch 17/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0414 - loss: -6.2931e-08
Epoch 18/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0393 - loss: -7.1991e-08
Epoch 19/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0389 - loss: -6.2028e-08
Epoch 20/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0419 - loss: -6.1959e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
[CV 2/3; 2/9] END .....batch_size=20, epochs=20;, score=0.041 total time=  35.4s
[CV 3/3; 2/9] START batch_size=20, epochs=20....................................
Epoch 1/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0354 - loss: 0.0518
Epoch 2/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0361 - loss: -4.6714e-08
Epoch 3/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0373 - loss: -4.8714e-08
Epoch 4/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0382 - loss: -5.6224e-08
Epoch 5/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0389 - loss: -4.8984e-08
Epoch 6/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0370 - loss: -6.5212e-08
Epoch 7/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0409 - loss: -6.1119e-08
Epoch 8/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0364 - loss: -6.9401e-08
Epoch 9/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0366 - loss: -6.2868e-08
Epoch 10/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0355 - loss: -6.3090e-08
Epoch 11/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0397 - loss: -6.6559e-08
Epoch 12/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0348 - loss: -7.1664e-08
Epoch 13/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0383 - loss: -6.2535e-08
Epoch 14/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0388 - loss: -6.4390e-08
Epoch 15/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0405 - loss: -6.5201e-08
Epoch 16/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0379 - loss: -6.8303e-08
Epoch 17/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0356 - loss: -6.4344e-08
Epoch 18/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0378 - loss: -6.2878e-08
Epoch 19/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0383 - loss: -6.2261e-08
Epoch 20/20
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0377 - loss: -6.6048e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[CV 3/3; 2/9] END .....batch_size=20, epochs=20;, score=0.037 total time=  30.5s
[CV 1/3; 3/9] START batch_size=20, epochs=40....................................
Epoch 1/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0395 - loss: 0.0462
Epoch 2/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0420 - loss: -5.8688e-08
Epoch 3/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0373 - loss: -5.3933e-08
Epoch 4/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0350 - loss: -5.8362e-08
Epoch 5/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0417 - loss: -6.2351e-08
Epoch 6/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0365 - loss: -5.9948e-08
Epoch 7/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0381 - loss: -5.9820e-08
Epoch 8/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0386 - loss: -6.0083e-08
Epoch 9/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0397 - loss: -6.9396e-08
Epoch 10/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0372 - loss: -6.1943e-08
Epoch 11/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0415 - loss: -5.7336e-08
Epoch 12/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0390 - loss: -5.6152e-08
Epoch 13/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0385 - loss: -6.2278e-08
Epoch 14/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0385 - loss: -6.2641e-08
Epoch 15/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0386 - loss: -6.0486e-08
Epoch 16/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0375 - loss: -6.2263e-08
Epoch 17/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0383 - loss: -6.4351e-08
Epoch 18/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0372 - loss: -6.8182e-08
Epoch 19/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0369 - loss: -5.9924e-08
Epoch 20/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0367 - loss: -6.0758e-08
Epoch 21/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0356 - loss: -5.9333e-08
Epoch 22/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0375 - loss: -6.8265e-08
Epoch 23/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0399 - loss: -6.8058e-08
Epoch 24/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0357 - loss: -6.8920e-08
Epoch 25/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0372 - loss: -6.7589e-08
Epoch 26/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0387 - loss: -6.3510e-08
Epoch 27/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0376 - loss: -6.6254e-08
Epoch 28/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0341 - loss: -5.9710e-08
Epoch 29/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0363 - loss: -6.0169e-08
Epoch 30/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0359 - loss: -6.3305e-08
Epoch 31/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0383 - loss: -6.3149e-08
Epoch 32/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.0380 - loss: -6.4587e-08
Epoch 33/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.0386 - loss: -6.4654e-08
Epoch 34/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0355 - loss: -6.1258e-08
Epoch 35/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0419 - loss: -6.1016e-08
Epoch 36/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0408 - loss: -5.9729e-08
Epoch 37/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0405 - loss: -7.0090e-08
Epoch 38/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0370 - loss: -5.8964e-08
Epoch 39/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0394 - loss: -6.2060e-08
Epoch 40/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0362 - loss: -6.6849e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
[CV 1/3; 3/9] END .....batch_size=20, epochs=40;, score=0.041 total time= 1.0min
[CV 2/3; 3/9] START batch_size=20, epochs=40....................................
Epoch 1/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.0416 - loss: 0.0429
Epoch 2/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0400 - loss: -6.3627e-08
Epoch 3/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0445 - loss: -6.2502e-08
Epoch 4/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0399 - loss: -6.4616e-08
Epoch 5/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0422 - loss: -6.4495e-08
Epoch 6/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0397 - loss: -6.1410e-08
Epoch 7/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0379 - loss: -5.9530e-08
Epoch 8/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0377 - loss: -6.3894e-08
Epoch 9/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0416 - loss: -6.8667e-08
Epoch 10/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0387 - loss: -6.4432e-08
Epoch 11/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0390 - loss: -6.4551e-08
Epoch 12/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0428 - loss: -6.3696e-08
Epoch 13/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0379 - loss: -6.1947e-08
Epoch 14/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0447 - loss: -6.2837e-08
Epoch 15/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0399 - loss: -6.2318e-08
Epoch 16/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0376 - loss: -6.4152e-08
Epoch 17/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0392 - loss: -6.7391e-08
Epoch 18/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0391 - loss: -5.9824e-08
Epoch 19/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0423 - loss: -6.5219e-08
Epoch 20/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0385 - loss: -6.3595e-08
Epoch 21/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0405 - loss: -6.2584e-08
Epoch 22/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0398 - loss: -5.9565e-08
Epoch 23/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0413 - loss: -6.7822e-08
Epoch 24/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0399 - loss: -6.4458e-08
Epoch 25/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0369 - loss: -6.0129e-08
Epoch 26/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0412 - loss: -6.2144e-08
Epoch 27/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0389 - loss: -6.2851e-08
Epoch 28/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0394 - loss: -5.6660e-08
Epoch 29/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0380 - loss: -6.0713e-08
Epoch 30/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0421 - loss: -6.2973e-08
Epoch 31/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0394 - loss: -6.2141e-08
Epoch 32/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0393 - loss: -6.5576e-08
Epoch 33/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.0418 - loss: -6.1732e-08
Epoch 34/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0401 - loss: -6.5212e-08
Epoch 35/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0405 - loss: -6.3697e-08
Epoch 36/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0405 - loss: -6.0381e-08
Epoch 37/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0399 - loss: -6.4803e-08
Epoch 38/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0416 - loss: -6.0197e-08
Epoch 39/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0386 - loss: -6.4920e-08
Epoch 40/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0384 - loss: -6.4339e-08
267/267 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step
[CV 2/3; 3/9] END .....batch_size=20, epochs=40;, score=0.041 total time= 1.1min
[CV 3/3; 3/9] START batch_size=20, epochs=40....................................
Epoch 1/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0399 - loss: 0.0541
Epoch 2/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0389 - loss: -5.5775e-08
Epoch 3/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0356 - loss: -5.7783e-08
Epoch 4/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0359 - loss: -5.4227e-08
Epoch 5/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0361 - loss: -6.1852e-08
Epoch 6/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.0371 - loss: -5.6343e-08
Epoch 7/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0363 - loss: -5.8568e-08
Epoch 8/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0369 - loss: -6.3724e-08
Epoch 9/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0393 - loss: -5.9807e-08
Epoch 10/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0376 - loss: -6.5235e-08
Epoch 11/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.0380 - loss: -6.8386e-08
Epoch 12/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0347 - loss: -6.1144e-08
Epoch 13/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0388 - loss: -6.3722e-08
Epoch 14/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0391 - loss: -7.0192e-08
Epoch 15/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0371 - loss: -6.9930e-08
Epoch 16/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0374 - loss: -6.5641e-08
Epoch 17/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.0360 - loss: -6.6440e-08
Epoch 18/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0380 - loss: -6.8787e-08
Epoch 19/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0358 - loss: -6.4403e-08
Epoch 20/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.0375 - loss: -6.8651e-08
Epoch 21/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0351 - loss: -7.0167e-08
Epoch 22/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0376 - loss: -7.1853e-08
Epoch 23/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.0385 - loss: -7.1166e-08
Epoch 24/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.0354 - loss: -6.9897e-08
Epoch 25/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.0368 - loss: -6.4310e-08
Epoch 26/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0383 - loss: -7.0555e-08
Epoch 27/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0402 - loss: -6.1855e-08
Epoch 28/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0394 - loss: -6.9977e-08
Epoch 29/40
534/534 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.0382 - loss: -6.2687e-08
Epoch 30/40

Summarize The Results

In [22]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : 0.03999992219236237, using {'batch_size': 20, 'epochs': 10}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 20, 'epochs': 10}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 20, 'epochs': 20}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 20, 'epochs': 40}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 25, 'epochs': 10}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 25, 'epochs': 20}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 25, 'epochs': 40}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 30, 'epochs': 10}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 30, 'epochs': 20}
0.03999992219236237,0.0019003177813329368 with: {'batch_size': 30, 'epochs': 40}

# Hyper Parameter Tuning Using Dropout And Learningate

In [23]:
from tensorflow.keras.layers import Dropout

def create_model(dropout_rate):
    model = Sequential()
    model.add(Dense(64,input_dim = 16,kernel_initializer = 'normal',activation = 'relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(32,input_dim = 16,kernel_initializer = 'normal',activation = 'relu'))
    model.add(Dropout(dropout_rate))
    model.add(Dense(1,activation = 'sigmoid'))
    return model

    # Create the model

model = KerasClassifier(model=create_model, loss="kl_divergence", optimizer="Adam", epochs=10, batch_size=20, verbose=0)

# Define the grid search parameters

learning_rate = [0.001,0.01,0.1]
dropout_rate = [0.0,0.1,0.2]



# Make a dictionary of the grid search parameters

param_grids = dict(optimizer__learning_rate = learning_rate,model__dropout_rate = dropout_rate)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model,param_grid = param_grids,cv = KFold(n_splits=3),verbose = 10)
grid_result = grid.fit(X_train,y_train)

Fitting 3 folds for each of 9 candidates, totalling 27 fits
[CV 1/3; 1/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.001.....
[CV 1/3; 1/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.001;, score=0.041 total time=  16.2s
[CV 2/3; 1/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.001.....
[CV 2/3; 1/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.001;, score=0.041 total time=  15.3s
[CV 3/3; 1/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.001.....
[CV 3/3; 1/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.001;, score=0.037 total time=  15.0s
[CV 1/3; 2/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.01......
[CV 1/3; 2/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.01;, score=0.041 total time=  14.2s
[CV 2/3; 2/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.01......
[CV 2/3; 2/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.01;, score=0.041 total time=  16.6s
[CV 3/3; 2/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.01......
[CV 3/3; 2/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.01;, score=0.037 total time=  13.3s
[CV 1/3; 3/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.1.......
[CV 1/3; 3/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.1;, score=0.041 total time=  15.0s
[CV 2/3; 3/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.1.......
[CV 2/3; 3/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.1;, score=0.041 total time=  13.2s
[CV 3/3; 3/9] START model__dropout_rate=0.0, optimizer__learning_rate=0.1.......
[CV 3/3; 3/9] END model__dropout_rate=0.0, optimizer__learning_rate=0.1;, score=0.037 total time=  12.5s
[CV 1/3; 4/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.001.....
[CV 1/3; 4/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.001;, score=0.041 total time=  14.4s
[CV 2/3; 4/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.001.....
[CV 2/3; 4/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.001;, score=0.041 total time=  15.1s
[CV 3/3; 4/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.001.....
[CV 3/3; 4/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.001;, score=0.037 total time=  15.1s
[CV 1/3; 5/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.01......
[CV 1/3; 5/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.01;, score=0.041 total time=  15.3s
[CV 2/3; 5/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.01......
[CV 2/3; 5/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.01;, score=0.041 total time=  13.9s
[CV 3/3; 5/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.01......
[CV 3/3; 5/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.01;, score=0.037 total time=  15.2s
[CV 1/3; 6/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.1.......
[CV 1/3; 6/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.1;, score=0.041 total time=  14.7s
[CV 2/3; 6/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.1.......
[CV 2/3; 6/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.1;, score=0.041 total time=  13.5s
[CV 3/3; 6/9] START model__dropout_rate=0.1, optimizer__learning_rate=0.1.......
[CV 3/3; 6/9] END model__dropout_rate=0.1, optimizer__learning_rate=0.1;, score=0.037 total time=  14.1s
[CV 1/3; 7/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.001.....
[CV 1/3; 7/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.001;, score=0.041 total time=  14.2s
[CV 2/3; 7/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.001.....
[CV 2/3; 7/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.001;, score=0.041 total time=  14.5s
[CV 3/3; 7/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.001.....
[CV 3/3; 7/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.001;, score=0.037 total time=  14.5s
[CV 1/3; 8/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.01......
[CV 1/3; 8/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.01;, score=0.041 total time=  15.2s
[CV 2/3; 8/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.01......
[CV 2/3; 8/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.01;, score=0.041 total time=  13.5s
[CV 3/3; 8/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.01......
[CV 3/3; 8/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.01;, score=0.037 total time=  15.0s
[CV 1/3; 9/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.1.......
[CV 1/3; 9/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.1;, score=0.041 total time=  14.6s
[CV 2/3; 9/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.1.......
[CV 2/3; 9/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.1;, score=0.041 total time=  13.6s
[CV 3/3; 9/9] START model__dropout_rate=0.2, optimizer__learning_rate=0.1.......
[CV 3/3; 9/9] END model__dropout_rate=0.2, optimizer__learning_rate=0.1;, score=0.037 total time=  15.6s

Summarize The Results

In [24]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : 0.03999992219236237, using {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.001}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.001}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.01}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.0, 'optimizer__learning_rate': 0.1}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.1, 'optimizer__learning_rate': 0.001}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.1, 'optimizer__learning_rate': 0.01}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.1, 'optimizer__learning_rate': 0.1}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.2, 'optimizer__learning_rate': 0.001}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.2, 'optimizer__learning_rate': 0.01}
0.03999992219236237,0.0019003177813329368 with: {'model__dropout_rate': 0.2, 'optimizer__learning_rate': 0.1}

# Hyper Parameter Tuning Using Activation Function and Kernel Initilizer

In [25]:
def create_model(activation_function,init):
    model = Sequential()
    model.add(Dense(64,input_dim = 16,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(0))
    model.add(Dense(32,input_dim = 16,kernel_initializer = init,activation = activation_function))
    model.add(Dropout(0))
    model.add(Dense(1,activation = 'sigmoid'))

    return model

# Create the model
adam= Adam(learning_rate=0.01)
model = KerasClassifier(model=create_model, loss="binary_crossentropy", optimizer=adam, epochs=10, batch_size=10, verbose=0)
# Define the grid search parameters
activation_function = ['softmax','relu','tanh','linear']
init = ['uniform','normal','zero']

# Make a dictionary of the grid search parameters
param_grids = dict(model__activation_function = activation_function,model__init = init)

# Build and fit the GridSearchCV

grid = GridSearchCV(estimator = model,param_grid = param_grids,cv = KFold(),verbose = 10)
grid_result = grid.fit(X_train,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 1/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.041 total time=  28.7s
[CV 2/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 2/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.043 total time=  31.5s
[CV 3/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 3/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.044 total time=  30.1s
[CV 4/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 4/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.036 total time=  26.9s
[CV 5/5; 1/12] START model__activation_function=softmax, model__init=uniform....
[CV 5/5; 1/12] END model__activation_function=softmax, model__init=uniform;, score=0.036 total time=  27.3s
[CV 1/5; 2/12] START model__activation_function=softmax, model__init=normal.....
[CV 1/5; 2/12] END model__activation_function=softmax, model__init=normal;, score=0.041 total time=  27.4s
[CV 2/5; 2/12] START model__activation_function=softmax, model__init=normal.....
[CV 2/5; 2/12] END model__activation_function=softmax, model__init=normal;, score=0.043 total time=  28.2s
[CV 3/5; 2/12] START model__activation_function=softmax, model__init=normal.....
[CV 3/5; 2/12] END model__activation_function=softmax, model__init=normal;, score=0.044 total time=  26.2s
[CV 4/5; 2/12] START model__activation_function=softmax, model__init=normal.....
[CV 4/5; 2/12] END model__activation_function=softmax, model__init=normal;, score=0.036 total time=  30.6s
[CV 5/5; 2/12] START model__activation_function=softmax, model__init=normal.....
[CV 5/5; 2/12] END model__activation_function=softmax, model__init=normal;, score=0.036 total time=  30.5s
[CV 1/5; 3/12] START model__activation_function=softmax, model__init=zero.......
[CV 1/5; 3/12] END model__activation_function=softmax, model__init=zero;, score=0.041 total time=  27.4s
[CV 2/5; 3/12] START model__activation_function=softmax, model__init=zero.......
[CV 2/5; 3/12] END model__activation_function=softmax, model__init=zero;, score=0.043 total time=  29.1s
[CV 3/5; 3/12] START model__activation_function=softmax, model__init=zero.......
[CV 3/5; 3/12] END model__activation_function=softmax, model__init=zero;, score=0.044 total time=  29.8s
[CV 4/5; 3/12] START model__activation_function=softmax, model__init=zero.......
[CV 4/5; 3/12] END model__activation_function=softmax, model__init=zero;, score=0.036 total time=  30.7s
[CV 5/5; 3/12] START model__activation_function=softmax, model__init=zero.......
[CV 5/5; 3/12] END model__activation_function=softmax, model__init=zero;, score=0.036 total time=  30.6s
[CV 1/5; 4/12] START model__activation_function=relu, model__init=uniform.......
[CV 1/5; 4/12] END model__activation_function=relu, model__init=uniform;, score=0.041 total time=  28.0s
[CV 2/5; 4/12] START model__activation_function=relu, model__init=uniform.......
[CV 2/5; 4/12] END model__activation_function=relu, model__init=uniform;, score=0.043 total time=  25.5s
[CV 3/5; 4/12] START model__activation_function=relu, model__init=uniform.......
[CV 3/5; 4/12] END model__activation_function=relu, model__init=uniform;, score=0.044 total time=  28.0s
[CV 4/5; 4/12] START model__activation_function=relu, model__init=uniform.......
[CV 4/5; 4/12] END model__activation_function=relu, model__init=uniform;, score=0.036 total time=  25.6s
[CV 5/5; 4/12] START model__activation_function=relu, model__init=uniform.......
[CV 5/5; 4/12] END model__activation_function=relu, model__init=uniform;, score=0.036 total time=  28.1s
[CV 1/5; 5/12] START model__activation_function=relu, model__init=normal........
[CV 1/5; 5/12] END model__activation_function=relu, model__init=normal;, score=0.041 total time=  28.3s
[CV 2/5; 5/12] START model__activation_function=relu, model__init=normal........
[CV 2/5; 5/12] END model__activation_function=relu, model__init=normal;, score=0.043 total time=  32.4s
[CV 3/5; 5/12] START model__activation_function=relu, model__init=normal........
[CV 3/5; 5/12] END model__activation_function=relu, model__init=normal;, score=0.044 total time=  25.0s
[CV 4/5; 5/12] START model__activation_function=relu, model__init=normal........
[CV 4/5; 5/12] END model__activation_function=relu, model__init=normal;, score=0.036 total time=  24.8s
[CV 5/5; 5/12] START model__activation_function=relu, model__init=normal........
[CV 5/5; 5/12] END model__activation_function=relu, model__init=normal;, score=0.036 total time=  28.7s
[CV 1/5; 6/12] START model__activation_function=relu, model__init=zero..........
[CV 1/5; 6/12] END model__activation_function=relu, model__init=zero;, score=0.041 total time=  28.6s
[CV 2/5; 6/12] START model__activation_function=relu, model__init=zero..........
[CV 2/5; 6/12] END model__activation_function=relu, model__init=zero;, score=0.043 total time=  26.9s
[CV 3/5; 6/12] START model__activation_function=relu, model__init=zero..........
[CV 3/5; 6/12] END model__activation_function=relu, model__init=zero;, score=0.044 total time=  25.3s
[CV 4/5; 6/12] START model__activation_function=relu, model__init=zero..........
[CV 4/5; 6/12] END model__activation_function=relu, model__init=zero;, score=0.036 total time=  27.5s
[CV 5/5; 6/12] START model__activation_function=relu, model__init=zero..........
[CV 5/5; 6/12] END model__activation_function=relu, model__init=zero;, score=0.036 total time=  31.0s
[CV 1/5; 7/12] START model__activation_function=tanh, model__init=uniform.......
[CV 1/5; 7/12] END model__activation_function=tanh, model__init=uniform;, score=0.041 total time=  28.0s
[CV 2/5; 7/12] START model__activation_function=tanh, model__init=uniform.......
[CV 2/5; 7/12] END model__activation_function=tanh, model__init=uniform;, score=0.043 total time=  27.2s
[CV 3/5; 7/12] START model__activation_function=tanh, model__init=uniform.......
[CV 3/5; 7/12] END model__activation_function=tanh, model__init=uniform;, score=0.044 total time=  27.4s
[CV 4/5; 7/12] START model__activation_function=tanh, model__init=uniform.......
[CV 4/5; 7/12] END model__activation_function=tanh, model__init=uniform;, score=0.036 total time=  26.4s
[CV 5/5; 7/12] START model__activation_function=tanh, model__init=uniform.......
[CV 5/5; 7/12] END model__activation_function=tanh, model__init=uniform;, score=0.036 total time=  30.1s
[CV 1/5; 8/12] START model__activation_function=tanh, model__init=normal........
[CV 1/5; 8/12] END model__activation_function=tanh, model__init=normal;, score=0.041 total time=  27.6s
[CV 2/5; 8/12] START model__activation_function=tanh, model__init=normal........
[CV 2/5; 8/12] END model__activation_function=tanh, model__init=normal;, score=0.043 total time=  25.3s
[CV 3/5; 8/12] START model__activation_function=tanh, model__init=normal........
[CV 3/5; 8/12] END model__activation_function=tanh, model__init=normal;, score=0.044 total time=  30.5s
[CV 4/5; 8/12] START model__activation_function=tanh, model__init=normal........
[CV 4/5; 8/12] END model__activation_function=tanh, model__init=normal;, score=0.036 total time=  29.3s
[CV 5/5; 8/12] START model__activation_function=tanh, model__init=normal........
[CV 5/5; 8/12] END model__activation_function=tanh, model__init=normal;, score=0.036 total time=  31.7s
[CV 1/5; 9/12] START model__activation_function=tanh, model__init=zero..........
[CV 1/5; 9/12] END model__activation_function=tanh, model__init=zero;, score=0.041 total time=  25.4s
[CV 2/5; 9/12] START model__activation_function=tanh, model__init=zero..........
[CV 2/5; 9/12] END model__activation_function=tanh, model__init=zero;, score=0.043 total time=  30.6s
[CV 3/5; 9/12] START model__activation_function=tanh, model__init=zero..........
[CV 3/5; 9/12] END model__activation_function=tanh, model__init=zero;, score=0.044 total time=  30.8s
[CV 4/5; 9/12] START model__activation_function=tanh, model__init=zero..........
[CV 4/5; 9/12] END model__activation_function=tanh, model__init=zero;, score=0.036 total time=  32.7s
[CV 5/5; 9/12] START model__activation_function=tanh, model__init=zero..........
[CV 5/5; 9/12] END model__activation_function=tanh, model__init=zero;, score=0.036 total time=  30.4s
[CV 1/5; 10/12] START model__activation_function=linear, model__init=uniform....
[CV 1/5; 10/12] END model__activation_function=linear, model__init=uniform;, score=0.041 total time=  27.6s
[CV 2/5; 10/12] START model__activation_function=linear, model__init=uniform....
[CV 2/5; 10/12] END model__activation_function=linear, model__init=uniform;, score=0.043 total time=  28.0s
[CV 3/5; 10/12] START model__activation_function=linear, model__init=uniform....
[CV 3/5; 10/12] END model__activation_function=linear, model__init=uniform;, score=0.044 total time=  30.4s
[CV 4/5; 10/12] START model__activation_function=linear, model__init=uniform....
[CV 4/5; 10/12] END model__activation_function=linear, model__init=uniform;, score=0.036 total time=  31.0s
[CV 5/5; 10/12] START model__activation_function=linear, model__init=uniform....
[CV 5/5; 10/12] END model__activation_function=linear, model__init=uniform;, score=0.036 total time=  30.7s
[CV 1/5; 11/12] START model__activation_function=linear, model__init=normal.....
[CV 1/5; 11/12] END model__activation_function=linear, model__init=normal;, score=0.041 total time=  30.7s
[CV 2/5; 11/12] START model__activation_function=linear, model__init=normal.....
[CV 2/5; 11/12] END model__activation_function=linear, model__init=normal;, score=0.043 total time=  27.1s
[CV 3/5; 11/12] START model__activation_function=linear, model__init=normal.....
[CV 3/5; 11/12] END model__activation_function=linear, model__init=normal;, score=0.044 total time=  25.1s
[CV 4/5; 11/12] START model__activation_function=linear, model__init=normal.....
[CV 4/5; 11/12] END model__activation_function=linear, model__init=normal;, score=0.036 total time=  31.3s
[CV 5/5; 11/12] START model__activation_function=linear, model__init=normal.....
[CV 5/5; 11/12] END model__activation_function=linear, model__init=normal;, score=0.036 total time=  30.9s
[CV 1/5; 12/12] START model__activation_function=linear, model__init=zero.......
[CV 1/5; 12/12] END model__activation_function=linear, model__init=zero;, score=0.041 total time=  25.7s
[CV 2/5; 12/12] START model__activation_function=linear, model__init=zero.......
[CV 2/5; 12/12] END model__activation_function=linear, model__init=zero;, score=0.043 total time=  27.5s
[CV 3/5; 12/12] START model__activation_function=linear, model__init=zero.......
[CV 3/5; 12/12] END model__activation_function=linear, model__init=zero;, score=0.044 total time=  25.6s
[CV 4/5; 12/12] START model__activation_function=linear, model__init=zero.......
[CV 4/5; 12/12] END model__activation_function=linear, model__init=zero;, score=0.036 total time=  26.4s
[CV 5/5; 12/12] START model__activation_function=linear, model__init=zero.......
[CV 5/5; 12/12] END model__activation_function=linear, model__init=zero;, score=0.036 total time=  24.6s

Summarize The reults

In [26]:
print('Best : {}, using {}'.format(grid_result.best_score_,grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
  print('{},{} with: {}'.format(mean, stdev, param))

Best : 0.04, using {'model__activation_function': 'softmax', 'model__init': 'uniform'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'softmax', 'model__init': 'uniform'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'softmax', 'model__init': 'normal'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'softmax', 'model__init': 'zero'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'relu', 'model__init': 'uniform'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'relu', 'model__init': 'normal'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'relu', 'model__init': 'zero'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'tanh', 'model__init': 'uniform'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'tanh', 'model__init': 'normal'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'tanh', 'model__init': 'zero'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'linear', 'model__init': 'uniform'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'linear', 'model__init': 'normal'}
0.04,0.0034403397361307225 with: {'model__activation_function': 'linear', 'model__init': 'zero'}